spring:
  application:
    name: ecomm-application
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommdb
    username: ecommuser
    password: ecommpass
#    url: jdbc:h2:mem:test

# Actuator configuration
# Official docs: https://docs.spring.io/spring-boot/reference/actuator/index.html
#                https://docs.spring.io/spring-boot/docs/2.0.x/actuator-api/html/
management:
  endpoints:
    web:
      exposure:
        include: '*' # expose all endpoints
        # exclude beans
        exclude: ['beans']
  endpoint:
    health:
      show-details: always # show detailed health information
    shutdown:
      access: read_only # allow shutdown endpoint to be accessed in read-only mode
  info:
    env:
      enabled: true

info:
  app:
    name: ecomm app
    description: Ecommerce application
    version: 1.0.0

server:
  shutdown: graceful